config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: {format: :json} do
    resources :ingredients, only: [:index]
    resources :fridge_items, only: [:create, :destroy, :index]
    resources :primaries, only: [:create, :destroy, :index]
  end


end

app/models/fridge_item.rb
class FridgeItem < ActiveRecord::Base

  belongs_to :user
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  has_many :fridge_items
  has_many :primaries
end

app/models/primary.rb
class Primary < ActiveRecord::Base
  belongs_to :user
  belongs_to :ingredient
end

app/models/user.rb
class User < ActiveRecord::Base
    attr_reader :password
    validates :username, :password_digest, :session_token, presence: true
    validates :username, uniqueness: true
    validates :password, length: {minimum: 6, allow_nil: true}

    after_initialize :ensure_session_token

    has_many :fridge_items

    has_many :fridge_ingredients,
    through: :fridge_items,
    source: :ingredient


    has_many :primaries

    has_many :primary_ingredients,
    through: :primaries,
    source: :ingredient

    def self.find_by_credentials(username, password)
      user = User.find_by(username: username)
      return nil unless user
      user.is_password?(password) ? user : nil
    end

    def password=(password)
      @password = password
      self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
      BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
      generate_session_token
      self.save!
      self.session_token
    end

    def ensure_session_token
      self.session_token ||= generate_session_token
    end

    private
    def generate_session_token
      self.session_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/api/fridge_items_controller.rb
class Api::FridgeItemsController < ApplicationController

  def create
    @fridge_item = FridgeItem.new(user_id: current_user.id, ingredient_id: params[:ingredient_id])
    if @fridge_item.save!
      render partial: "api/ingredients/ingredient", locals: {ingredient: @fridge_item.ingredient}
    else
      flash.now[:errors] = @fridge_item.errors.full_messages
    end
  end

  def destroy
    @fridge_item = FridgeItem.find_by(user_id: current_user.id, ingredient_id: params[:ingredient_id])
    @fridge_item.delete
    render partial: "api/ingredients/ingredient", locals: {ingredient: @fridge_item.ingredient}
  end

  def index
    @fridge_items = current_user.fridge_items
  end

end

app/controllers/api/ingredients_controller.rb
class Api::IngredientsController < ApplicationController

  def index
    if params[:query] == "fridge"
      @ingredients = current_user.fridge_ingredients
    elsif params[:query] == "primary"
      @ingredients = current_user.primary_ingredients
    else
      @ingredients = Ingredient.all - current_user.fridge_ingredients - current_user.primary_ingredients
    end
  end

end

app/controllers/api/primaries_controller.rb
class Api::PrimariesController < ApplicationController

  def create
    @primary = Primary.new(user_id: current_user.id, ingredient_id: params[:ingredient_id])
    if @primary.save!
      render partial: "api/ingredients/ingredient", locals: {ingredient: @primary.ingredient}
    else
      flash.now[:errors] = @primary.errors.full_messages
    end
  end

  def destroy
    @primary = Primary.find_by(user_id: current_user.id, ingredient_id: params[:ingredient_id])
    @primary.delete
    render partial: "api/ingredients/ingredient", locals: {ingredient: @primary.ingredient}
  end

  def index
    @primarys = current_user.primaries
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login!(user)
    @current_user = user
    session[:session_token] = current_user.reset_session_token!
  end

  def logged_in?
    !current_user.nil?
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_user
    redirect_to new_user_url unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password])
    if @user
      login!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = ["Incorrect Username/Password"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :require_user

  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end


end

app/helpers/api/fridge_items_helper.rb
module Api::FridgeItemsHelper
end

app/helpers/api/ingredients_helper.rb
module Api::IngredientsHelper
end

app/helpers/api/primaries_helper.rb
module Api::PrimariesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FoodieFridge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-72919213-1', 'auto');
    ga('send', 'pageview');

  </script>
</head>
<body>

<div class='user-pane'>
  <% if current_user %>

    <header class="header">
      <nav class="header-nav group">
        <a href="/"><img class="fridge-logo" src="assets/FoodieFridge-logo.png"/></a>


        <ul class="header-list group">
          <div class="hello-username item header-words">
            Welcome
            <%= current_user.username %>
          </div>

          <%= link_to "About", "#my-modal", :class => "item about header-words", "data-toggle" => "modal" %>
          <div class="modal fade" id="my-modal" title="About" onclick="ga('send', 'event', 'External Link', 'FoodieFridge', 'Modal');">

            <div class="modal-header">
              <button aria-hidden="true" class="close" data-dismiss="modal" type="button">×</button>
              <img class="fridge-logo about-fridge" src="assets/FoodieFridge-logo.png"/>
            </div>

            <div class="modal-body">
              Users can search through millions of recipes gathered from every corner of the
              internet. Recipes can be found and filtered by placing ingredients into "All My Ingredients" or "Required Ingredients".<br/><br/>
              <strong><h3>How it works:</h3></strong>
              Drag and drop recipe tiles into the "All My Ingredients" or "Required Ingredients" boxes to search for recipes.</br>
              <strong>All My Ingredients:</strong> FoodieFridge will return up to 10 recipes for EACH item in this category.<br/>
              <strong>Required Ingredients:</strong> Every recipe search result will contain ALL ingredients in this category.</br></br>
              FoodieFridge was created by Chris Umbach using Ruby on Rails and React.js. You can view the source code on <a href="https://github.com/cumbach/FoodieFridge">Github</a>.<br/>
              <a href="http://www.chrisumbach.com/">Click Here</a> to view Chris's other projects or to get in touch.
            </div>

            <div class="modal-footer">
              <button aria-hidden="true" class="btn" data-dismiss="modal">Close</button>
            </div>
          </div>


          <div class="item logout-button">
            <%= button_to "Log out", session_url, method: :delete %>
          </div>

        </ul>
      </nav>
    </header>


  <% end %>
</div>

<br>

<%= yield %>

<br>


</body>
</html>

app/views/shared/_auth.html.erb
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
  <%= error %>
  <% end %>
<% end %>

app/views/static_pages/root.html.erb
<div id='root'></div>

app/views/users/new.html.erb
<form class="input-group user-auth" action=<%= users_url %> method="post">
  <img class="user-auth-logo" src="/assets/FoodieFridge-logo.png" />

  <% if flash[:errors] %>
    <div class="alert alert-danger text-center" role="alert">
      <% flash[:errors].each do |error| %>
        <%= error %> <br>
      <% end %>
    </div>
  <% end %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input class="form-control" type="text" name=user[username] value="" id="username" placeholder="Username">
  <br>
  <br>
  <input class="form-control" type="password" name=user[password] value="" id="password" placeholder="Password">
  <br>
  <br>
  <input class="form-control purple-button" type="submit" name="name" value="Sign Up">
  <br>
  <br>
  <p>
    <%= link_to "Already have an account? Sign in", new_session_url %>
  </p>
</form>

<form class="input-group demo-form" action=<%= users_url %> method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name=user[username] value="<%= "Guest" + rand(1..100000).to_s %>">
  <input type="hidden" name=user[password] value="password">
  <input class="btn demo-btn" type="submit" value="Sign in as Guest">
</form>